project:
  type: book

book:
  title: "Landscape characteristics influence projected growth rates of stream-resident juvenile salmon in the face of climate change in the Kenai River watershed, southcentral Alaska"
  subtitle: "Analytical white paper supporting Meyer et al. 2023 (Transactions of the American Fisheries Society)"
  author: "Benjamin Meyer"
  date: today
  repo-url: https://github.com/bmeyer/kenai_juv_salmon_growth_analyses
  chapters:
    - index.qmd
    - study-area-methods.qmd
    - diet-literature-review.qmd
    - diet-composition.qmd
    - bioenergetics-inputs-observed.qmd
    - bioenergetics-inputs-projected.qmd
    - simulation-results.qmd
    - references.qmd


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    number-sections: true
